### ISSUE TITLE
Allow skipping the commit hash

### ISSUE THREAD

**Issue by diamondburned** [diamondburned/nix-bonito#1]
`bonito` should allow this:

```toml
[root.channels]
 nixos = "github:NixOS/nixpkgs nixos-unstable"
```

Which should result in a `channels."github:nixpkgs/NixOS nixos-unstable".url` having a URL with a commit hash pointing to the latest commit of the GitHub repository at the time `bonito -u` was invoked.
